server.port=8080

spring.application.name=demo

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.url=jdbc:mysql://localhost:3306/base?createDatabaseIfNotExist=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


jwt.secret=RZJlhIsQr4HQSgjFdlzbcCF04AeQr2DbBPjhPJmuRKU3CFVbDhaRCvBsrR67oAgJ
arquivamento.path=C:/var